# Generated by Django 6.0.3 on 2026-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=20)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
