# Generated by Django 5.2.12 on 2026-04-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0002_alter_socio_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
