# Generated by Django 5.2.12 on 2026-04-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0003_alter_socio_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="cursos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diretoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=200)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="diretoria/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Esporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="esportes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="historia/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="noticias/"),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="parceiros/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Socio",
        ),
    ]
