# Generated by Django 6.0.3 on 2026-04-05 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0004_curso_diretoria_esporte_evento_historia_membro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="clientes/"),
                ),
                ("site", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Doacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("valor_sugerido", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="doacoes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("numero_socio", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("senha", models.CharField(max_length=100)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="socios/")),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        default="Inativo",
                        max_length=20,
                    ),
                ),
                (
                    "investimento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Diretoria",
        ),
        migrations.DeleteModel(
            name="Evento",
        ),
        migrations.DeleteModel(
            name="Historia",
        ),
        migrations.DeleteModel(
            name="Membro",
        ),
        migrations.RenameField(
            model_name="noticia",
            old_name="descricao",
            new_name="texto",
        ),
        migrations.RemoveField(
            model_name="parceiro",
            name="link",
        ),
        migrations.AddField(
            model_name="historico",
            name="socio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="associacao.socio"
            ),
        ),
    ]
