# Generated by Django 6.0.5 on 2026-07-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0005_cliente_doacao_historico_socio_delete_diretoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentificacaoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                (
                    "remote_addr",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
