# Generated by Django 6.0.5 on 2026-07-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0006_identificacaolog"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="pagamento_agosto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_dezembro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_julho",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_junho",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_novembro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_outubro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_setembro",
            field=models.BooleanField(default=False),
        ),
    ]
