# Generated by Django 6.0.5 on 2026-07-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0007_socio_pagamento_agosto_socio_pagamento_dezembro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="pagamento_abril",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_fevereiro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_janeiro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_maio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socio",
            name="pagamento_marco",
            field=models.BooleanField(default=False),
        ),
    ]
