# Generated by Django 6.0.5 on 2026-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0008_socio_pagamento_abril_socio_pagamento_fevereiro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("texto", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="historias/"),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
