# Generated by Django 6.0.5 on 2026-07-28 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0009_historia"),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="data",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="historico",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="historicos/"),
        ),
        migrations.AddField(
            model_name="historico",
            name="texto",
            field=models.TextField(blank=True, null=True),
        ),
    ]
