# Generated by Django 6.0.3 on 2026-08-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0010_historico_data_historico_imagem_historico_texto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diretoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=200)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="diretoria/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
            ],
        ),
    ]
