# Generated by Django - add valor field to Curso

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associacao", "0011_diretoria_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=400.0,
                max_digits=8,
                verbose_name="Valor (R$)",
            ),
        ),
    ]
